version: '3'

services:
  mongodb:
    image: mongo:latest
    networks:
      - my_network
    volumes:
      - data:/data/db
  web:
    build: .
    container_name: td6
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
      - ./display.txt:/app/display.txt
    environment:
      - MONGO_URI=mongodb://mongodb:27017/test_db
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
volumes:
  data:
